[package]
name = "ogcapi-processes"
version = "0.2.0"
license.workspace = true
repository.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
default = ["greeter", "geojson-loader", "gdal-loader"]
greeter = []
geojson-loader = ["dep:geojson", "dep:geo", "dep:wkb", "dep:sqlx", "dep:ogcapi-drivers"]
gdal-loader = ["dep:arrow", "dep:gdal", "dep:geo", "dep:wkb", "dep:sqlx", "dep:ogcapi-drivers"]

[dependencies]
anyhow = "1.0"
arrow ={ version = "54.0.0", optional = true, features = ["ffi"] }
async-trait = "0.1.84"
dyn-clone = "1.0.17"
gdal = { version = "0.17.1", optional = true, features = ["bindgen"] }
geo = { version = "0.29.3", optional = true }
geojson = { workspace = true, optional = true, features = ["geo-types"]}
http-body = "1.0.1"
schemars = "0.8.21"
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

sqlx = { version = "0.8.3", optional = true }
wkb = { version = "0.8.0", optional = true }

ogcapi-types = { path = "../ogcapi-types", version = "0.2", features = ["processes"] }
ogcapi-drivers = { path = "../ogcapi-drivers", version = "0.2", optional = true, features = ["postgres", "common"] }

[dev-dependencies]
tokio = { version = "1.42", features = ["full"] }
