###

GET http://localhost:8484/processes

###

GET https://maps.gnosis.earth/ogcapi/processes/echo

###

GET http://localhost:8484/processes/echo

###

POST https://maps.gnosis.earth/ogcapi/processes/echo/execution

{
  "process" : "https://maps.gnosis.earth/ogcapi/processes/echo",
  "inputs" : {
    "stringInput" : "Value1"
  },
  "response": "raw"
}

###

POST https://maps.gnosis.earth/ogcapi/processes/echo/execution

{
  "process" : "https://maps.gnosis.earth/ogcapi/processes/echo",
  "inputs" : {
    "stringInput" : "Value1",
    "doubleInput" : 2.0
  },
  "response": "raw"
}

###

POST https://maps.gnosis.earth/ogcapi/processes/echo/execution

{
  "process" : "https://maps.gnosis.earth/ogcapi/processes/echo",
  "inputs" : {
    "stringInput" : "Value1",
    "dateInput" : "2025-10-10"
  },
  "response": "raw"
}

###

POST http://localhost:8484/processes/echo/execution
Content-Type: application/json

{
  "inputs" : {
    "stringInput" : "Value1",
    "doubleInput" : 2.0
  },
  "response": "raw"
}

###

POST https://maps.gnosis.earth/ogcapi/processes/echo/execution

{
  "process" : "https://maps.gnosis.earth/ogcapi/processes/echo",
  "inputs" : {
    "stringInput" : "Value1",
    "doubleInput" : 2.0
  },
  "response": "document"
}

###

POST https://maps.gnosis.earth/ogcapi/processes/echo/execution

{
  "process" : "https://maps.gnosis.earth/ogcapi/processes/echo",
  "inputs" : {
    "stringInput" : "Value1",
    "doubleInput" : 2.0
  },
  "outputs" : {
    "stringOutput" : {
      "transmissionMode" : "value"
    },
    "doubleOutput" : {
      "transmissionMode" : "value"
    }
  },
  "response": "raw"
}

###

POST http://localhost:8484/processes/echo/execution
Content-Type: application/json

{
  "process" : "https://maps.gnosis.earth/ogcapi/processes/echo",
  "inputs" : {
    "stringInput" : "Value1"
  },
  "response": "raw"
}

###

POST https://maps.gnosis.earth/ogcapi/processes/echo/execution
Content-Type: application/json

{
  "inputs" : {
    "stringInput" : "teststring"
  },
  "outputs" : {
    "stringOutput" : {
      "transmissionMode" : "value"
    }
  }
}


###

POST http://localhost:8484/processes/echo/execution

{
  "inputs" : {
    "stringInput" : "teststring"
  },
  "outputs" : {
    "stringOutput" : {
      "transmissionMode" : "value"
    }
  }
}

###

GET http://localhost:8484/jobs/1
Content-Type: application/json

###

GET http://localhost:8484/api

###

GET http://localhost:8484/conformance

###

GET https://maps.gnosis.earth/ogcapi/conformance

###

GET https://demo.pygeoapi.io/cite/conformance

###

GET https://demo.pygeoapi.io/cite/processes/

###

GET https://demo.pygeoapi.io/cite/processes/hello-world

###

POST https://demo.pygeoapi.io/cite/processes/hello-world/execution
Content-Type: application/json
Prefer: respond-async

{
  "inputs" : {
    "name" : "teststring"
  },
  "outputs" : {
    "greeting" : {
      "transmissionMode" : "value"
    }
  },
  "response" : "raw"
}

# {
#   "id": "b7fbc875-a9d4-11f0-b3cf-5deaf93487b7",
#   "status": "accepted",
#   "type": "process"
# }

###

POST https://demo.pygeoapi.io/cite/processes/hello-world/execution
Content-Type: application/json

{
  "inputs" : {
    "name" : "teststring"
  },
  "outputs" : {
    "greeting" : {
      "transmissionMode" : "value"
    }
  }
}

###

POST https://demo.pygeoapi.io/cite/processes/hello-world/execution
Content-Type: application/json

{
  "inputs" : {
    "name" : "teststring"
  }
}

###

POST https://demo.pygeoapi.io/cite/processes/hello-world/execution
Content-Type: application/json

{
  "inputs" : {
    "name" : "teststring"
  },
  "response" : "document"
}

###

GET https://demo.pygeoapi.io/cite/jobs/bd5643f4-ad83-11f0-88d7-fd14cd9c1ea6/results

###

GET https://demo.pygeoapi.io/cite/jobs/b7fbc875-a9d4-11f0-b3cf-5deaf93487b7

# {
#   "type": "process",
#   "processID": "hello-world",
#   "jobID": "b7fbc875-a9d4-11f0-b3cf-5deaf93487b7",
#   "status": "successful",
#   "message": "Job complete",
#   "progress": 100,
#   "parameters": null,
#   "created": "2025-10-15T14:39:13.337938Z",
#   "started": "2025-10-15T14:39:13.337972Z",
#   "finished": "2025-10-15T14:39:13.345850Z",
#   "updated": "2025-10-15T14:39:13.345884Z",
#   "links": [
#     {
#       "href": "https://demo.pygeoapi.io/cite/jobs/b7fbc875-a9d4-11f0-b3cf-5deaf93487b7/results?f=html",
#       "rel": "http://www.opengis.net/def/rel/ogc/1.0/results",
#       "type": "text/html",
#       "title": "Results of job as HTML"
#     },
#     {
#       "href": "https://demo.pygeoapi.io/cite/jobs/b7fbc875-a9d4-11f0-b3cf-5deaf93487b7/results?f=json",
#       "rel": "http://www.opengis.net/def/rel/ogc/1.0/results",
#       "type": "application/json",
#       "title": "Results of job as JSON"
#     }
#   ]
# }

###

POST http://localhost:8484/processes/echo/execution
Content-Type: application/json

{
  "inputs" : {
    "stringInput" : "teststring"
  },
  "outputs" : {
    "stringOutput" : {
      "transmissionMode" : "value"
    }
  },
  "response" : "raw"
}

###

POST http://localhost:8484/processes/echo/execution
Content-Type: application/json
Prefer: respond-async

{
  "inputs" : {
    "stringInput" : "teststring"
  },
  "outputs" : {
    "stringOutput" : {
      "transmissionMode" : "value"
    }
  }
}

###

GET http://localhost:8484/jobs

###

GET http://localhost:8484/jobs/d9bbfa6c-b6cd-4fc4-a086-a4586c5baaea/results

###

POST http://maps.gnosis.earth/ogcapi/processes/echo/execution
Content-Type: application/json

{
  "inputs" : {
    "boundingBoxInput": {
      "bbox": [ 51.9, 7, 52, 7.1 ],
      "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
    }
  }
}

###

POST http://localhost:8123/processes/echo/execution
Content-Type: application/json

{
  "inputs" : {
    "stringInput" : "teststring"
  },
  "outputs" : {
    "stringOutput" : {
      "transmissionMode" : "value"
    }
  },
  "response" : "raw"
}
